from fastapi import FastAPI, Depends, HTTPException
from fastapi.middleware.cors import CORSMiddleware # Add this import
from sqlalchemy.orm import Session
from pydantic import BaseModel
from typing import Optional
from sqlalchemy import or_

# Import our database connection and models
import models
from database import engine, SessionLocal

# 1. CREATE THE DATABASE TABLES
# This line automatically creates the 'westcubes_league.db' file 
# and all the tables (teams, players, matches) if they don't exist yet.
models.Base.metadata.create_all(bind=engine)

# 2. INITIALIZE FASTAPI
app = FastAPI(title="Westcubes Premier Football League API")

# --- ADD THIS CORS BLOCK ---
app.add_middleware(
    CORSMiddleware,
    allow_origins=["http://localhost:5173"], # Your React frontend URL
    allow_credentials=True,
    allow_methods=["*"], # Allows GET, POST, PUT, DELETE, etc.
    allow_headers=["*"],
)
# ---------------------------

# 3. DATABASE DEPENDENCY
# This safely opens and closes a connection to the database for every web request
def get_db():
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()

# 4. DATA VALIDATION SCHEMAS (Pydantic)
# This ensures that when someone tries to create a team, they MUST provide a name.
class TeamCreate(BaseModel):
    name: str
    manager_name: str

# 5. OUR API ENDPOINTS
@app.get("/")
def health_check():
    return {"status": "Online", "league": "Westcubes Premier Football League"}

@app.post("/teams/")
def register_team(team: TeamCreate, db: Session = Depends(get_db)):
    # First, check if a team with this name already exists
    existing_team = db.query(models.Team).filter(models.Team.name == team.name).first()
    if existing_team:
        raise HTTPException(status_code=400, detail="A team with this name is already registered.")
    
    # Create and save the new team
    new_team = models.Team(name=team.name, manager_name=team.manager_name)
    db.add(new_team)
    db.commit()
    db.refresh(new_team) # Gets the new ID generated by the database
    
    return new_team

@app.get("/teams/")
def list_teams(db: Session = Depends(get_db)):
    # Query the database to get all records inside the teams table
    teams = db.query(models.Team).all()
    return teams

# =====================================================================
# MATCH SCHEMA (Data Validation)
# This section defines the exact blueprint of the data we expect from 
# the frontend when recording a new match. 
# =====================================================================
class MatchCreate(BaseModel):
    home_team_id: int
    away_team_id: int
    home_goals: int
    away_goals: int

# =====================================================================
# MATCH ENDPOINT (Business Logic)
# This section handles the POST request to save a completed match into
# the database securely.
# =====================================================================
@app.post("/matches/")
def record_match(match: MatchCreate, db: Session = Depends(get_db)):
    
    # 1. Validate that the match makes logical sense
    if match.home_team_id == match.away_team_id:
        raise HTTPException(status_code=400, detail="A team cannot play against itself.")
    
    # 2. Prepare the data for the database using our SQLAlchemy model
    new_match = models.Match(
        home_team_id=match.home_team_id,
        away_team_id=match.away_team_id,
        home_goals=match.home_goals,
        away_goals=match.away_goals
    )
    
    # 3. Stage, commit, and refresh the database transaction
    db.add(new_match)
    db.commit()
    db.refresh(new_match)
    
    # 4. Return the successfully saved database record back to the frontend
    return new_match

# =====================================================================
# STANDINGS ENDPOINT (Business Logic & Data Aggregation)
# This section calculates the entire league table dynamically based on
# the raw match data stored in the database.
# =====================================================================
@app.get("/standings/")
def get_standings(db: Session = Depends(get_db)):
    # 1. Fetch raw data from the database
    teams = db.query(models.Team).all()
    matches = db.query(models.Match).all()
    
    # 2. Initialize a dictionary to hold calculated stats for each team
    # Using team_id as the key for lightning-fast lookups
    standings_data = {
        team.id: {
            "id": team.id,
            "name": team.name,
            "played": 0, "won": 0, "drawn": 0, "lost": 0,
            "goalsFor": 0, "goalsAgainst": 0, "goalDifference": 0, "points": 0
        } for team in teams
    }
    
    # 3. Process every match to calculate wins, losses, and goals
    for match in matches:
        home = standings_data.get(match.home_team_id)
        away = standings_data.get(match.away_team_id)
        
        # Skip if a team was deleted but the match still exists
        if not home or not away: 
            continue
            
        # Update Matches Played
        home["played"] += 1
        away["played"] += 1
        
        # Update Goals Scored and Conceded
        home["goalsFor"] += match.home_goals
        home["goalsAgainst"] += match.away_goals
        away["goalsFor"] += match.away_goals
        away["goalsAgainst"] += match.home_goals
        
        # Determine the winner and distribute points
        if match.home_goals > match.away_goals:
            home["won"] += 1
            home["points"] += 3
            away["lost"] += 1
        elif match.home_goals < match.away_goals:
            away["won"] += 1
            away["points"] += 3
            home["lost"] += 1
        else:
            home["drawn"] += 1
            home["points"] += 1
            away["drawn"] += 1
            away["points"] += 1
            
    # 4. Calculate Goal Difference and sort the final table
    for stats in standings_data.values():
        stats["goalDifference"] = stats["goalsFor"] - stats["goalsAgainst"]
        
    # Sort mathematically: Priority 1: Points, Priority 2: Goal Diff, Priority 3: Goals For
    sorted_standings = sorted(
        standings_data.values(), 
        key=lambda x: (x["points"], x["goalDifference"], x["goalsFor"]), 
        reverse=True
    )
    
    return sorted_standings

# 1. SCHEMAS: Define the structure for player data.
class PlayerCreate(BaseModel):
    name: str
    position: str
    squad_number: int
    team_id: int # This ensures we link the player to a valid team

# 2. ENDPOINT: Save the player to the database.
@app.post("/players/")
def register_player(player: PlayerCreate, db: Session = Depends(get_db)):
    # Create the player instance using our SQLAlchemy model
    new_player = models.Player(
        name=player.name,
        position=player.position,
        squad_number=player.squad_number,
        team_id=player.team_id
    )
    
    # Standard DB operation: Add, Commit, Refresh
    db.add(new_player)
    db.commit()
    db.refresh(new_player)
    
    return new_player

# =====================================================================
# GET PLAYERS BY TEAM ENDPOINT
# Fetches players specifically linked to a given team_id.
# =====================================================================
@app.get("/teams/{team_id}/players/")
def get_players_by_team(team_id: int, db: Session = Depends(get_db)):
    # 1. Query the Player table specifically for the requested team_id
    # We use .filter() here instead of fetching all players and filtering in Python.
    # This is highly efficient because the database engine does the work,
    # minimizing memory usage in our Python application.
    players = db.query(models.Player).filter(models.Player.team_id == team_id).all()
    
    # 2. Return the filtered list
    return players

# =====================================================================
# GET MATCH HISTORY BY TEAM ENDPOINT
# Fetches all matches where the specific team played (Home or Away).
# =====================================================================
@app.get("/teams/{team_id}/matches/")
def get_matches_by_team(team_id: int, db: Session = Depends(get_db)):
    # Efficiently query matches where team_id matches home OR away.
    # The database executes this as a single indexed query.
    matches = db.query(models.Match).filter(
        or_(
            models.Match.home_team_id == team_id,
            models.Match.away_team_id == team_id
        )
    ).all()
    return matches

# DELETE EDNPOINTS

@app.delete("/teams/{team_id}")
def delete_team(team_id: int, db: Session = Depends(get_db)):
    team = db.query(models.Team).filter(models.Team.id == team_id).first()
    if not team:
        raise HTTPException(status_code=404, detail="Team not found")
    db.delete(team) # Cascades will auto-delete players/matches!
    db.commit()
    return {"message": "Team and all related data deleted"}

@app.delete("/players/{player_id}")
def delete_player(player_id: int, db: Session = Depends(get_db)):
    player = db.query(models.Player).filter(models.Player.id == player_id).first()
    if not player:
        raise HTTPException(status_code=404, detail="Player not found")
    db.delete(player)
    db.commit()
    return {"message": "Player deleted"}

@app.delete("/matches/{match_id}")
def delete_match(match_id: int, db: Session = Depends(get_db)):
    match = db.query(models.Match).filter(models.Match.id == match_id).first()
    if not match:
        raise HTTPException(status_code=404, detail="Match not found")
    db.delete(match)
    db.commit()
    return {"message": "Match deleted"}

# Pydantic schemas for partial updates
class TeamUpdate(BaseModel):
    name: Optional[str] = None
    manager_name: Optional[str] = None

@app.patch("/teams/{team_id}")
def update_team(team_id: int, team_update: TeamUpdate, db: Session = Depends(get_db)):
    # 1. Fetch existing record
    db_team = db.query(models.Team).filter(models.Team.id == team_id).first()
    if not db_team:
        raise HTTPException(status_code=404, detail="Team not found")

    # 2. Update fields only if they are provided in the request
    if team_update.name:
        db_team.name = team_update.name
    if team_update.manager_name:
        db_team.manager_name = team_update.manager_name

    db.commit()
    db.refresh(db_team)
    return db_team