from fastapi import FastAPI, Depends, HTTPException
from fastapi.middleware.cors import CORSMiddleware # Add this import
from sqlalchemy.orm import Session
from pydantic import BaseModel

# Import our database connection and models
import models
from database import engine, SessionLocal

# 1. CREATE THE DATABASE TABLES
# This line automatically creates the 'westcubes_league.db' file 
# and all the tables (teams, players, matches) if they don't exist yet.
models.Base.metadata.create_all(bind=engine)

# 2. INITIALIZE FASTAPI
app = FastAPI(title="Westcubes Premier Football League API")

# --- ADD THIS CORS BLOCK ---
app.add_middleware(
    CORSMiddleware,
    allow_origins=["http://localhost:5173"], # Your React frontend URL
    allow_credentials=True,
    allow_methods=["*"], # Allows GET, POST, PUT, DELETE, etc.
    allow_headers=["*"],
)
# ---------------------------

# 3. DATABASE DEPENDENCY
# This safely opens and closes a connection to the database for every web request
def get_db():
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()

# 4. DATA VALIDATION SCHEMAS (Pydantic)
# This ensures that when someone tries to create a team, they MUST provide a name.
class TeamCreate(BaseModel):
    name: str
    manager_name: str

# 5. OUR API ENDPOINTS
@app.get("/")
def health_check():
    return {"status": "Online", "league": "Westcubes Premier Football League"}

@app.post("/teams/")
def register_team(team: TeamCreate, db: Session = Depends(get_db)):
    # First, check if a team with this name already exists
    existing_team = db.query(models.Team).filter(models.Team.name == team.name).first()
    if existing_team:
        raise HTTPException(status_code=400, detail="A team with this name is already registered.")
    
    # Create and save the new team
    new_team = models.Team(name=team.name, manager_name=team.manager_name)
    db.add(new_team)
    db.commit()
    db.refresh(new_team) # Gets the new ID generated by the database
    
    return new_team